name: Test

on:
  push:
    branches:
      - develop
      - alpha
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      
      - name: Install node modules
        run: |
          npm install
          
      - name: Run test
        run: |
          npm test